server:
  port: 8080

spring:
  application:
    name: stream-backend

  datasource:
    url: jdbc:mysql://localhost:3306/test_schema
    username: root
    password: dejanfrancu7
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

cors:
  allowed-origins:
    - "http://localhost:4200"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed-headers:
    - "*"

jwt:
  secret: "secret-key"
  expiration: 3600000
